BusBuggy/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('accounts.urls', namespace='profiles')),
    path("", include('core.urls', namespace='core')),
    path("", include('hiring.urls', namespace='hire')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    
    path('', views.index_views, name='home'),
    
    path('events/information', views.event_views, name='info'),
    
    path('booking/bus/search/<slug>', views.add_to_bookings, name='addhire'),
    
    path('bus/register', views.bus_hire_view, name='bookbus'),
    
    path('aboutus', views.aboutUs_page, name='about'),
    
    path('faQ', views.faQ_page, name='faQ'),
        
    path('booking/bus/search', views.SearchView.as_view(), name='searchpath'),
    
    path('booking/<int:pk>', views.BookingBusDetail.as_view(), name='bookingdetail'),
    
    path("booking/bus/direction/<int:pk>/<slug>", views.DirectionDetail.as_view(), name="direction_detail"),

    # path('hiring', views.hirebus, name='hiringbus'),

    # path('booking', booking_views, name='book'),
    
    # path(
        
    #     "informaa1276765433niaganalanajanaanaianau34aranaeanawana324apanaoana456543akanqanyana56banatanhanaban45456774",

    #     name='booked'
    
    # )
    
]

hiring/urls.py
from django.urls import path
from . import views

app_name = 'hire'

urlpatterns = [
    path('ordering/form/orderbus', views.hirebuses, name='hirebus'),
]

core/models.py
import datetime

from django.shortcuts import reverse
from django.db import models
from django.utils import timezone
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

from accounts.models import User
from location_app.models import Location, Directions

# Create your models here.

class EventType(models.Model):
    name =  models.CharField(max_length=252)
    images = models.ImageField(upload_to='events_folder/', default='fixed_pic.jpg')
    descriptions = models.TextField(max_length=1330)
    slug = models.SlugField()
    
    def __str__(self):
        return self.name


class BusNumber(models.Model):
    bus_number = models.IntegerField(default=22)
    
    def __str__(self):
        number = self.bus_number
        return str(number)



class BookingBus(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    direction = models.ForeignKey(Directions, on_delete=models.CASCADE)
    hired = models.BooleanField(default=False)
    start_date = models.DateTimeField(auto_now_add=True)
    hired_date = models.DateTimeField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse("core:home", kwargs={
            'slug': self.slug
        })

    class Meta:
        verbose_name_plural = 'HiringBus'

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.user.username

hiring/models.py
import datetime

from django.shortcuts import reverse
from django.db import models
from django.db.models import Q

from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from accounts.models import User
from location_app.models import Location, Directions
from core.models import BusNumber, EventType






class HiringBus(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    event_type = models.ForeignKey(

        EventType,
        on_delete=models.CASCADE,
        default='others'
    )
    
    how_many_bus_are_needed = models.ForeignKey(

        BusNumber,
        related_name='bus_needed',
        on_delete=models.DO_NOTHING,
        default='1'
    )
    
    number_of_sitters = models.ForeignKey(

        BusNumber,
        on_delete=models.DO_NOTHING,
        default='22'
    )

    particular_location_address = models.CharField(max_length=325)
    location_LGA = models.ForeignKey(Directions, on_delete=models.CASCADE)
    
    event_destination_address = models.CharField(max_length=325)
    event_LGA = models.ForeignKey(Directions, related_name='event_LG', on_delete=models.CASCADE)
    
    set_date_and_time = models.DateTimeField(_("Date_and_time"), blank=True, null=True)
    
    booked_date = models.DateTimeField(auto_now_add=True)
    update_date_time = models.DateTimeField('date published', auto_now=True)
    
    is_booked = models.BooleanField(default=False)
    
    slug = models.SlugField()

    class Meta:
        verbose_name_plural = 'BookingBus'
 
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


    def __str__(self):
        return self.event_type.name + " by " + self.user.username

    def __unicode__(self):
        return self.event_type.name + " by " + self.user.username

location_app/models.py
from django.db import models





class Location(models.Model):
    
    # longtitude = models.IntegerField()
    # lagtitude = models.IntegerField()

    address = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=200)

    # ip = models.GenericIPAddressField()

    def __str__(self):
        return self.address
    # + ", " + self.city + ", " + self.state



class DirectionManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (
               Q(title__icontains=query)
            #    Q(your_location=query)
            #    Q(destination__icontains=query)
            )
            qs = qs.filter(or_lookup).distinct()
        return qs



class Directions(models.Model):
    title = models.CharField(max_length=200)
    price = models.FloatField()
    location_img = models.ImageField(upload_to='direction_img', blank=True)
    discount_price = models.FloatField(blank=True, null=True)
    your_location = models.ForeignKey(Location, related_name='user_locations', on_delete=models.DO_NOTHING)
    destination = models.ForeignKey(Location, on_delete=models.DO_NOTHING)
    slug = models.SlugField()
    
    objects = DirectionManager()
    
    class Meta:
        verbose_name_plural = 'Directions'
    
    def __str__(self):
        return self.title
    
    def get_add_to_bookings_url(self):
        return reverse(
        "core:addhire",
        kwargs= {
            "slug":self.slug
        }
    )
    def get_absolute_url(self):
        return reverse("core:direction_detail", kwargs={
            "pk": self.pk,
            "slug":self.slug
        })

core/forms.py
from django import forms
# from .models import BookingBus

# class BookingBForm(forms.ModelForm):
    
#     class Meta:
#         model = HiringB
#         fields = [
#             'your_location',
#             'destination',
#         ]
#     def clean(self, *args, **kwargs):
#         return super(BookingBForm, self).clean(*args, **kwargs)

# class HiringBForm(forms.ModelForm):
    
#     class Meta:
#         model = BookingBus
#         fields = [
#             'event_type',
#             'how_many_bus_are_needed',
#             'number_of_sitters',
#             'particular_locations',
#             'destination',
#             'date_and_time'
#         ]

hiring/forms.py
from django import forms
from .models import HiringBus

class HiringBForm(forms.ModelForm):
    
    class Meta:
        model = HiringBus
        fields = [
            'event_type',
            'how_many_bus_are_needed',
            'number_of_sitters',
            'particular_location_address',
            'location_LGA',
            'event_destination_address',
            'event_LGA',
            'set_date_and_time',
        ]

core/views.py
from itertools import chain

from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist

from accounts.models import User
from location_app.models import Location, Directions

from .models import (
    
    BookingBus,
    
    EventType
    
    )



    
# this is the homepage
# @login_required
def index_views(request):
    
    # user = User.objects.get(username=request.user)
    
    booked_b = Directions.objects.all()[:3]
    
    context = {
        
        'book_b': booked_b,
        
    }
    return render(request, 'home_templates/index.html', context)





# this is the bus search and book pages
class SearchView(ListView):
    
    template_name = 'home_templates/searchpage.html'
    
    paginate_by = 20
    
    count = 0
    
    # for getting context_data
    def get_context_data(self, *args, **kwargs):
        
        context = super().get_context_data(*args, **kwargs)
        
        context['count'] = self.count or 0
        
        context['query'] = self.request.GET.get('q')
        
        return context
    
    # for getting queryset
    def get_queryset(self):
        
        request = self.request
        
        query = request.GET.get('q', None)
        
        if query is not None:
            
            direction_results = Directions.objects.search(query)
            
            queryset_chain = chain(
                
                direction_results,
                
            )
            qs = sorted(
                
                queryset_chain,
                
                key=lambda instance: instance.pk,
                
                reverse=True
            )
            
            self.count = len(qs)
            
            return qs
        
        return Directions.objects.none()



# this is for viewing events
@login_required
def event_views(request):
    
    user = User.objects.get(username=request.user)
    
    # booked_b = BookingB.objects.all()
    
    hire_b = HiringBus.objects.filter(user=user)
    
    context = {
        # 'book_b': booked_b,
        'hire_b': hire_b
    }
    return render(request, 'home_templates/booked.html', context)




def bus_hire_view(request):
    bus_directions = Directions.objects.all()[:8]
    
    context = {
        
        'bus_directions':bus_directions
        
    }
    return render(request, 'home_templates/bookbus.html', context)



#used to book for bus 
@login_required
def add_to_bookings(request, slug):
    directions = get_object_or_404(Directions, slug=slug)

    hire_qs = BookingBus.objects.filter(
        
        user=request.user,
        
        direction=directions,
        
        hired=True
        
    )

    if hire_qs.exists():
        
        messages.info(request, 'this booking already exist')
        
        return redirect('/home', slug=slug)
    
    else:
        
        hire_bus, created = HiringBus.objects.get_or_create(
            
            user=request.user,
            
            direction=directions,
            
            hired=True
            
        )[:2]
        
        hire_bus.save()
        
        messages.info(
            
            request,
            
            'Your Booking was Successful, Feel Free to book another'
            
        )  
    return redirect('/home', slug=slug)


    
    
    # hire_qs = Hiring.objects.filter(user=request.user, hired=True)
    # if hire_qs.exists():
    #     hire = hire_qs[0]
    #     #check if the hiring bus is in the hire
    #     if hire.direction.filter(direction__slug=directions.slug).exists():
    #         hire_bus
        


# Create your views here.
# @login_required
# def booking_views(request):
    # if request.method == 'POST':
    #     book_form = BookingBForm(request.POST)
    #     if book_form.is_valid():
    #         your_locations = book_form.cleaned_data.get('your_location')
    #         destinations = book_form.cleaned_data.get('destination')
    #         users = User.objects.get(username=request.user)
    #         book_saver = HiringB.objects.create(
    #             user=request.user,
    #             your_location=your_locations,
    #             destination=destinations
    #         )
    #         book_saver.save()
    #         # book_form.instance = request.user
    #         # book_form.save()
    #         return redirect('/events/information')
    # else:
    #     book_form = BookingBForm()
    # context = {
    #     'book_form':book_form
    # }
    # return render(request, 'about.html', context)
    # return render(request, 'home_templates/booking.html', context)





def aboutUs_page(request):
    
    return render(request, 'order/about.html')

def faQ_page(request):
    
    return render(request, 'order/faQ.html')

class BookingBusDetail(DetailView):
    
    model = BookingBus
    
    template_name='applications/properties-single.html'

class DirectionDetail(DetailView):
    
    model = Directions
    
    template_name = 'applications/direction-single.html'

hiring/views.py
from itertools import chain

from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages

from accounts.models import User
from location_app.models import Location, Directions
from core.models import EventType
from .models import HiringBus
from .forms import HiringBForm


def hirebuses(request):
    
    hiring_data = Location.objects.all()
    hiring_info = EventType.objects.all()
    
    if request.method == 'POST':
        hirebus_form = HiringBForm(request.POST)

        if hirebus_form.is_valid():
            event_type = hirebus_form.cleaned_data.get(
                'event_type' 
            )
            needed_amount_of_bus = hirebus_form.cleaned_data.get(
                'how_many_bus_are_needed'
            )
            number_of_sitters = hirebus_form.cleaned_data.get(
                'number_of_sitters'
            )
            particular_location_address = hirebus_form.cleaned_data.get(
                'particular_location_address'
            )
            location_LGA = hirebus_form.cleaned_data.get(
                'location_LGA'
            )
            event_destination_address = hirebus_form.cleaned_data.get(
                'event_destination_address'
            )
            event_LGA = hirebus_form.cleaned_data.get(
                'event_LGA'
            )
            date_and_time = hirebus_form.cleaned_data.get(
                'set_date_and_time'
            )
            hirebus_form = HiringBus.objects.create(

                user=request.user,
                event_type=event_type,
                how_many_bus_are_needed=needed_amount_of_bus,
                number_of_sitters=number_of_sitters,
                particular_location_address=particular_location_address,
                location_LGA=location_LGA,
                event_destination_address=event_destination_address,
                event_LGA=event_LGA,
                set_date_and_time=date_and_time,

            )
            # hirebus_form.instance = request.user
            hirebus_form.save()
            
            return redirect('/home', hirebus_form)
        
    else:
        
        hirebus_form = HiringBForm()
        
    context = {
        
        'hirebus_data': hiring_data,
        
        "hirebus_form": hirebus_form,
        
        'hiring_info': hiring_info
    }
    
    return render(request, 'hiring/hiringforms.html', context)

core/templates/hiring/base.html
{% load static %}
<!DOCTYPE html>
<html>
    {% include "hiring/head.html" %}
<body>
    {% block blockbody %}
    
    {% endblock blockbody %}
{% include "hiring/scripts.html" %}
</body>
</html>

core/templates/hiring/head.html
<!-- start head -->
{% load static %}
<head>
    <meta charset="utf-8">
    <title>FormWizard_v4</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="busbuggy" content="busbuggy.com">
    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
    <!-- MATERIAL DESIGN ICONIC FONT -->
    <link rel="stylesheet" href="{% static 'book/css/bootstrap.min.css' %}">

    <!-- DATE-PICKER -->
    <!-- <link rel="stylesheet" href="{% static 'book/vendor/date-picker/css/datepicker.min.css' %}"> -->

    <!-- STYLE CSS -->
    <link rel="stylesheet"
      href=" {% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %} ">
    <link rel="stylesheet" href="{% static 'book/css/style.css' %}">

    	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<!-- end head -->

core/templates/hiring/hiringform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="", method="POST">
        {% csrf_token %}
        {% for hire in hirebus_form %}
          {{ hire }}
        {% endfor %}
        <button type="submit">Submit</button>
    </form>
</body>

</html>

core/templates/hiring/hiringforms.html
{% extends 'hiring/base.html' %}
{% load static %}

{% block blockbody %}
<header>
	<h1>BusBuggy</h1>
	<div class="ic">
		<i  class="fa fa-arrow-right" style="color: #fff;"></i>
	</div>
</header>

	<div id="booking" class="section">
		<div class="section-center">
			<div class="container">
				<form action="" method="post">
					{% csrf_token %}
				<div class="col-md-7 col-md-push-5" id="first_text">
					<div class="booking-cta">
						<h1 class="titles">Make your reservation</h1>
						<p>
							Lorem ipsum dolor sit amet consectetur adipisicing elit. 
						</p>
					</div>
				</div>
				<div class="col-md-4 col-md-pull-7" id="first_page">
					<div class="booking-form">
					
						<!-- <div class="form-group">
							<span class="form-label">Your Destination</span>
							<input class="form-control" type="text" placeholder="Enter a destination or hotel name">
						</div>
						<div class="row">
							<div class="col-sm-6">
								<div class="form-group">
									<span class="form-label">Check In</span>
									<input class="form-control" type="date" required>
								</div>
							</div>
							<div class="col-sm-6">
								<div class="form-group">
									<span class="form-label">Check out</span>
									<input class="form-control" type="date" required>
								</div>
							</div>
						</div> -->
						<div class="row">
							<div class="col-sm-12">
								<div class="form-group">
									<span class="form-label">Rooms</span>
									<select class="form-control" name="destination" required id="id_destination">
										{% for locate in hirebus_data %}
										  	<option value=" {{locate.id}} ">{{ locate.address }}</option>
										{% endfor %}

										<!-- <option>2</option>
										<option>3</option> -->
									</select>
									<span class="select-arrow"></span>
								</div>
							</div>
							<div class="col-sm-12">
								<div class="form-group">
									<span class="form-label">Adults</span>
									<select class="form-control" name="particular_locations" required id="id_particular_locations">
										
										{% for particular in hirebus_data %}
											<option value=" {{particular.id}} ">{{ particular.address }}</option>
										{% endfor %}
											

										<!-- <option>2</option>
										<option>3</option> -->
									</select>
									<span class="select-arrow"></span>
								</div>
								<div class="row">
									<div class="col-sm-12">
										<div class="form-group">
											<span class="form-label">Check In</span>
											<input class="form-control" name="date_and_time" id="id_date_and_time" type="date" required>
										</div>
									</div>

								</div>
							</div>


					
						<div class="form-btn">
							<a class="submit-btn"   id="first_btn">Continue</a>
						</div>
						</div>
					</div>
				</div>
				<div class="col-md-7 col-md-push-5" id="second_text">
					<div class="booking-cta">
						<h1>Get The Best from Us</h1>
						<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi facere, soluta magnam consectetur
							molestias itaque
							ad sint fugit architecto incidunt iste culpa perspiciatis possimus voluptates aliquid consequuntur
							cumque quasi.
							Perspiciatis.
						</p>
					</div>
				</div>
					<div class="col-md-4 col-md-pull-7" id="second_page" >
						<div class="booking-form">

								<div class="row">
									<div class="col-sm-12">
										<div class="form-group">
											<span class="form-label">Rooms</span>
											<select class="form-control" name="event_type" id="id_event_type">
												{% for events in hiring_info %}
													<option value=" {{ events.id }} ">{{ events.name }}</option>												  
												{% endfor %}

												<!-- <option>2</option>
												<option>3</option> -->
											</select>
											<span class="select-arrow"></span>
										</div>
									</div>
									<div class="col-sm-12">
										<div class="form-group">
											<span class="form-label">Adults</span>
											<select class="form-control" name="how_many_bus_are_needed" id="id_how_many_bus_are_needed">
												<option value="1">22</option>

												<option value="2">34</option>

												<option value="3">56</option>

												<option value="4">10</option>

												<option value="5">22</option>

												<option value="6">9</option>

												<option value="7">8</option>

												<option value="8">5</option>

												<option value="9">4</option>

												<option value="10">3</option>

												<option value="11">2</option>

												<option value="12">1</option>
											</select>
											<span class="select-arrow"></span>
										</div>
									</div>
									<div class="col-sm-12">
										<div class="form-group">
											<span class="form-label">Children</span>
											<select class="form-control" name="number_of_sitters" id="id_number_of_sitters">
												<option value="1">22</option>

												<option value="2">34</option>

												<option value="3">56</option>

												<option value="4">10</option>

												<option value="5">22</option>

												<option value="6">9</option>

												<option value="7">8</option>

												<option value="8">5</option>

												<option value="9">4</option>

												<option value="10">3</option>

												<option value="11">2</option>

												<option value="12">1</option>
											</select>
											<span class="select-arrow"></span>
										</div>
									</div>
								</div>
								<div class="form-btn">
									<a class="submit-btn" style=" background-color: aqua;">back</a>
									<button type="submit" class="submit-btn">Book Now</button>
								</div>

						</div>

					</div>
				</form>
			</div>
		</div>
	</div>
  {% endblock blockbody %}

core/templates/hiring/scripts.html
{% load static %}
<!-- start script -->
<script src="{% static 'book/js/jquery-3.2.1.min.js' %}"></script>

<!-- JQUERY STEP -->
<script src="{% static 'book/js/jquery-migrate-3.0.1.min.js' %}"></script>


<script src="{% static 'book/js/main.js' %}"></script>
<!-- endscript -->