BusBuggy/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('accounts.urls', namespace='profiles')),
    path("", include('core.urls', namespace='core')),
    path("", include('hiring.urls', namespace='hire')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    
    path('', views.index_views, name='home'),
    
    path('events/information', views.event_views, name='info'),
    
    path('booking/bus/search/<slug>', views.add_to_bookings, name='addhire'),
    
    path('bus/register', views.bus_hire_view, name='bookbus'),
    
    path('aboutus', views.aboutUs_page, name='about'),
    
    path('faQ', views.faQ_page, name='faQ'),
        
    path('booking/bus/search', views.SearchView.as_view(), name='searchpath'),
    
    path('booking/<int:pk>', views.BookingBusDetail.as_view(), name='bookingdetail'),
    
    path("booking/bus/direction/<int:pk>/<slug>", views.DirectionDetail.as_view(), name="direction_detail"),

    # path('hiring', views.hirebus, name='hiringbus'),

    # path('booking', booking_views, name='book'),
    
    # path(
        
    #     "informaa1276765433niaganalanajanaanaianau34aranaeanawana324apanaoana456543akanqanyana56banatanhanaban45456774",

    #     name='booked'
    
    # )
    
]

core/models.py
import datetime

from django.shortcuts import reverse
from django.db import models
from django.utils import timezone
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

from accounts.models import User
from location_app.models import Location, Directions

# Create your models here.

class EventType(models.Model):
    name =  models.CharField(max_length=252)
    images = models.ImageField(upload_to='events_folder/', default='fixed_pic.jpg')
    descriptions = models.TextField(max_length=1330)
    slug = models.SlugField()
    
    def __str__(self):
        return self.name


class BusNumber(models.Model):
    bus_number = models.IntegerField(default=22)
    
    def __str__(self):
        number = self.bus_number
        return str(number)



class BookingBus(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    direction = models.ForeignKey(Directions, on_delete=models.CASCADE)
    hired = models.BooleanField(default=False)
    start_date = models.DateTimeField(auto_now_add=True)
    hired_date = models.DateTimeField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse("core:home", kwargs={
            'slug': self.slug
        })

    class Meta:
        verbose_name_plural = 'HiringBus'

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.user.username

core/forms.py
from django import forms
# from .models import BookingBus

# class BookingBForm(forms.ModelForm):
    
#     class Meta:
#         model = HiringB
#         fields = [
#             'your_location',
#             'destination',
#         ]
#     def clean(self, *args, **kwargs):
#         return super(BookingBForm, self).clean(*args, **kwargs)

# class HiringBForm(forms.ModelForm):
    
#     class Meta:
#         model = BookingBus
#         fields = [
#             'event_type',
#             'how_many_bus_are_needed',
#             'number_of_sitters',
#             'particular_locations',
#             'destination',
#             'date_and_time'
#         ]

core/views.py
from itertools import chain

from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist

from accounts.models import User
from location_app.models import Location, Directions

from .models import (
    
    BookingBus,
    
    EventType
    
    )



    
# this is the homepage
# @login_required
def index_views(request):
    
    # user = User.objects.get(username=request.user)
    
    booked_b = Directions.objects.all()[:3]
    
    context = {
        
        'book_b': booked_b,
        
    }
    return render(request, 'home_templates/index.html', context)





# this is the bus search and book pages
class SearchView(ListView):
    
    template_name = 'home_templates/searchpage.html'
    
    paginate_by = 20
    
    count = 0
    
    # for getting context_data
    def get_context_data(self, *args, **kwargs):
        
        context = super().get_context_data(*args, **kwargs)
        
        context['count'] = self.count or 0
        
        context['query'] = self.request.GET.get('q')
        
        return context
    
    # for getting queryset
    def get_queryset(self):
        
        request = self.request
        
        query = request.GET.get('q', None)
        
        if query is not None:
            
            direction_results = Directions.objects.search(query)
            
            queryset_chain = chain(
                
                direction_results,
                
            )
            qs = sorted(
                
                queryset_chain,
                
                key=lambda instance: instance.pk,
                
                reverse=True
            )
            
            self.count = len(qs)
            
            return qs
        
        return Directions.objects.none()



# this is for viewing events
@login_required
def event_views(request):
    
    user = User.objects.get(username=request.user)
    
    # booked_b = BookingB.objects.all()
    
    hire_b = HiringBus.objects.filter(user=user)
    
    context = {
        # 'book_b': booked_b,
        'hire_b': hire_b
    }
    return render(request, 'home_templates/booked.html', context)




def bus_hire_view(request):
    bus_directions = Directions.objects.all()[:8]
    
    context = {
        
        'bus_directions':bus_directions
        
    }
    return render(request, 'home_templates/bookbus.html', context)



#used to book for bus 
@login_required
def add_to_bookings(request, slug):
    directions = get_object_or_404(Directions, slug=slug)

    hire_qs = BookingBus.objects.filter(
        
        user=request.user,
        
        direction=directions,
        
        hired=True
        
    )

    if hire_qs.exists():
        
        messages.info(request, 'this booking already exist')
        
        return redirect('/home', slug=slug)
    
    else:
        
        hire_bus, created = HiringBus.objects.get_or_create(
            
            user=request.user,
            
            direction=directions,
            
            hired=True
            
        )[:2]
        
        hire_bus.save()
        
        messages.info(
            
            request,
            
            'Your Booking was Successful, Feel Free to book another'
            
        )  
    return redirect('/home', slug=slug)


    
    
    # hire_qs = Hiring.objects.filter(user=request.user, hired=True)
    # if hire_qs.exists():
    #     hire = hire_qs[0]
    #     #check if the hiring bus is in the hire
    #     if hire.direction.filter(direction__slug=directions.slug).exists():
    #         hire_bus
        


# Create your views here.
# @login_required
# def booking_views(request):
    # if request.method == 'POST':
    #     book_form = BookingBForm(request.POST)
    #     if book_form.is_valid():
    #         your_locations = book_form.cleaned_data.get('your_location')
    #         destinations = book_form.cleaned_data.get('destination')
    #         users = User.objects.get(username=request.user)
    #         book_saver = HiringB.objects.create(
    #             user=request.user,
    #             your_location=your_locations,
    #             destination=destinations
    #         )
    #         book_saver.save()
    #         # book_form.instance = request.user
    #         # book_form.save()
    #         return redirect('/events/information')
    # else:
    #     book_form = BookingBForm()
    # context = {
    #     'book_form':book_form
    # }
    # return render(request, 'about.html', context)
    # return render(request, 'home_templates/booking.html', context)





def aboutUs_page(request):
    
    return render(request, 'order/about.html')

def faQ_page(request):
    
    return render(request, 'order/faQ.html')

class BookingBusDetail(DetailView):
    
    model = BookingBus
    
    template_name='applications/properties-single.html'

class DirectionDetail(DetailView):
    
    model = Directions
    
    template_name = 'applications/direction-single.html'

core/templates/home_templates/bookbus.html
{% extends "base_folder/base.html" %}
{% load static %}
{% block blockbody %}
<!-- START nav -->
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="/home">BusBuggy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
            aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span>
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="/home" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="/about" class="nav-link">About</a></li>
                <li class="nav-item"><a href="/events" class="nav-link">Events</a></li>
                <li class="nav-item"><a href="/" class="nav-link"></a></li>
            </ul>
            <span><a href="/accounts/login" class="btn btn-sm btn-primary">LOGIN</a></span>
        </div>

    </div>
</nav>
<!-- END nav -->
<section class="hero-wrap hero-wrap-2 ftco-degree-bg js-fullheight"
    style="background-image: url({% static 'images/bg_1.jpg' %});" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i
                                class="ion-ios-arrow-forward"></i></a></span> <span>Personnal Booking <i
                            class="ion-ios-arrow-forward"></i></span></p>
                <h1 class="mb-3 bread">Successfull Booking <br> a Bus Here</h1>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row">

            {% for direction in bus_directions %}
            <!-- START event tab -->
            
            <div class="col-md-4">
                <div class="property-wrap ftco-animate">
                    <!-- <a href="#" class="img" style="background-image: url({% static 'images/work-1.jpg' %});"></a> -->
                    <div class="text">
                        <p class="price"><span class="old-price"></span><span
                                class="orig-price">N{{ direction.price }}<small></small></span></p>
                        <ul class="property_list">
                            <li><span class="flaticon-floor-plan"></span>{{ direction.user.username }}</li>
                        </ul>
                        <h3><a href="#">{{ direction.your_location }}</a></h3>
                        <span class="location">{{ direction.destination }}</span>
                        <a href="" class="d-flex align-items-center justify-content-center btn-sm bg-primary">
                            <!-- <span class="ion-ios-link"></span> -->
                            <span style="color: white;">Booked</span>
                        </a>
                    </div>
                </div>
            </div>
            <!-- END event tab -->
            {% endfor %}
        </div>
        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">
                    <ul>
                        <li><a href="#">&lt;</a></li>
                        <li class="active"><span>1</span></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">&gt;</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock blockbody %}

core/templates/home_templates/booked.html
{% extends "base_folder/base.html" %}
{% load static %}
{% block blockbody %}
<!-- START nav -->
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <a class="navbar-brand" href="/home">BusBuggy</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span>
    </button>

    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active"><a href="/home" class="nav-link">Home</a></li>
        <li class="nav-item"><a href="/about" class="nav-link">About</a></li>
        <li class="nav-item"><a href="/events" class="nav-link">Events</a></li>
        <li class="nav-item"><a href="/" class="nav-link"></a></li>
      </ul>
      <span><a href="/accounts/login" class="btn btn-sm btn-primary">LOGIN</a></span>
    </div>

  </div>
</nav>
<!-- END nav -->
<section class="hero-wrap hero-wrap-2 ftco-degree-bg js-fullheight"
  style="background-image: url({% static 'images/bg_1.jpg' %});" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center">
      <div class="col-md-9 ftco-animate pb-5 text-center">
        <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i
                class="ion-ios-arrow-forward"></i></a></span> <span>Personnal Booking <i
              class="ion-ios-arrow-forward"></i></span></p>
        <h1 class="mb-3 bread">Successfull Booking <br> a Bus Here</h1>
      </div>
    </div>
  </div>
</section>

<section class="ftco-section">
  <div class="container">
    <div class="row">

      {% for hire in hire_b %}
      <!-- START event tab -->

      <div class="col-md-4">
        <div class="property-wrap ftco-animate">
          <!-- <a href="#" class="img" style="background-image: url({% static 'images/work-1.jpg' %});"></a> -->
          <div class="text">
            <p class="price"><span class="old-price"></span><span class="orig-price">N5,000<small>.00</small></span></p>
            <ul class="property_list">
              <li><span class="flaticon-floor-plan"></span>{{ hire.user.username }}</li>
            </ul>
            <h3><a href="#">{{ hire.your_location }}</a></h3>
            <span class="location">{{ hire.destination }}</span>
            <a href="" class="d-flex align-items-center justify-content-center btn-sm bg-primary">
              <!-- <span class="ion-ios-link"></span> -->
              <span style="color: white;">Booked</span>
            </a>
          </div>
        </div>
      </div>
      <!-- END event tab -->
      {% endfor %}
    </div>
    <div class="row mt-5">
      <div class="col text-center">
        <div class="block-27">
          <ul>
            <li><a href="#">&lt;</a></li>
            <li class="active"><span>1</span></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#">&gt;</a></li>
          </ul>
        </div>
      </div>
    </div>
    </div>
    </section>
{% endblock blockbody %}

core/templates/home_templates/booking.html
{% extends 'base_folder/base.html' %}
{% load static %}
{% block blockbody %}
    <!-- START nav -->
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="/home">BusBuggy</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active"><a href="/home" class="nav-link">Home</a></li>
                    <li class="nav-item"><a href="/about" class="nav-link">About</a></li>
                    <li class="nav-item"><a href="/events" class="nav-link">Events</a></li>
                    <li class="nav-item"><a href="/" class="nav-link"></a></li>
                </ul>
            </div>
            <span><a href="/accounts/login" class="btn btn-sm btn-primary">LOGIN</a></span>
        </div>
    </nav>
    <!-- END nav -->

    <section class="ftco-section contact-section" style="background-image: url({% static 'images/bg_1.jpg' %});">
        <div class="container">

            <div class="row block-9 justify-content-center mb-5">
                <div class="col-md-8 mb-md-5">
                    <h2 class="text-center">HIRE A BUS <br>quick and easy from your location to your destination.
                    </h2>
                    <form method="POST" class="bg-light p-5 contact-form">
                        {% csrf_token %}

                        {% for book in book_form %}
                        <div class="form-group">
                            {{ book }}
                        </div>
                        {% endfor %}
                        <!-- <div class="form-group">

                        </div> -->
                        <div class="form-group">
                            <input type="submit" value="Book Now" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <div id="map" class="bg-white"></div>
                </div>
            </div>
        </div>
    </section>
    <!-- <div class="form-group">
        <input type="text" class="form-control" placeholder="Your location">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Your destination">
    </div> -->
{% endblock blockbody %}

core/templates/home_templates/searchpage.html
{% extends "base_folder/base.html" %}
{% load static %}
{% block blockbody %}

<!-- START nav -->
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <img src="{% static 'images/logo-1.png' %}" style="width: 60px;" alt="">
    <a class="navbar-brand" href="/home">BusBuggy</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span>
    </button>

    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active"><a href="/home" class="nav-link">Home</a></li>
        <li class="nav-item"><a href="/aboutus" class="nav-link">About</a></li>
        <li class="nav-item"><a href="/events/information" class="nav-link">Booked</a></li>
        <li class="nav-item"><a href="{% url 'core:searchpath' %}" class="nav-link">Search</a></li>
        {% if user.is_authenticated %}
        <li class="nav-item"><a href="/profile/{{user}}" class="nav-link">Profile</a></li>
        {% endif %}
        <li class="nav-item"><a href="" class="nav-link"></a></li>
      </ul>
      {% if user.is_authenticated %}
      <a href="/accounts/logout">LOGOUT</a>
      {% else %}
      <span><a href="/accounts/login" class="btn btn-lg rounded-pill btn-primary">LOGIN</a></span>
      {% endif %}

    </div>

  </div>
</nav>
<!-- END nav -->
    <div class="hero-wrap ftco-degree-bg" style="background:url({% static 'images/level2.jpg' %}) ;"  data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text justify-content-center align-items-center">
          <div class="col-lg-8 col-md-6 ftco-animate d-flex align-items-end">
          	<div class="text text-center">
              
              {% if count < 1 %}
                <h1 class="mb-4">The Simplest <br>Way to Find Your Location</h1>
              {% else %}
                <h1 class="mb-4">{{ count }} results for <b>{{ query }}</b></h1>              
              {% endif %}

	            <p style="font-size: 18px;">We create a search request by their place and supplies it 
                with the necessary destination. It is a paradisematic country, in which roasted parts</p>
              <form action=" {% url 'core:searchpath' %} " 
              method="GET" class="search-location mt-md-5">
		        		<div class="row justify-content-center">
		        			<div class="col-lg-10 align-items-end">
		        				<div class="form-group">
		          				<div class="form-field">
				                <input type="text" name="q" class="form-control" id="id_q" placeholder="Search location">
				                <button><span class="ion-ios-search"></span></button>
				              </div>
			              </div>
		        			</div>
		        		</div>
		        	</form>
            </div>
          </div>
        </div>
      </div>
    </div>

  
    

<section class="ftco-section">
  <div class="container">
    <div class="row">
{% for object in object_list %}
            <!-- START event tab -->
            
            <div class="col-md-4">
              <div class="property-wrap ftco-animate">
                <!-- <a href="#" class="img" style="background-image: url({% static 'images/work-1.jpg' %});"></a> -->
                <div class="text">
                  <p class="price"><span class="old-price"></span><span
                      class="orig-price">N{{ object.price }}<small></small></span></p>
                  <ul class="property_list">
                    <li><span class="flaticon-floor-plan"></span>{{ object.title }}</li>
                  </ul>
                  <h3><a href="#">{{ object.your_location }}</a></h3>
                  <span class="location">{{ object.destination }}</span>
                  <a href="/booking/{{object.slug}}" class="d-flex align-items-center justify-content-center btn-sm bg-primary">
                    <!-- <span class="ion-ios-link"></span> -->
                    <span style="color: white;">Book Now</span>
                  </a>
                </div>
              </div>
            </div>
            <!-- END event tab -->
{% endfor %}
            </div>
                <div class="row mt-5">
                  <div class="col text-center">
                    <div class="block-27">
                      <ul>
                        <li><a href="#">&lt;</a></li>
                        <li class="active"><span>1</span></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">&gt;</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
                </div>
                </section>

{% endblock blockbody %}