BusBuggy/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('accounts.urls', namespace='profiles')),
    path("", include('core.urls', namespace='core')),
    path("", include('hiring.urls', namespace='hire')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    
    path('', views.index_views, name='home'),
    
    path('events/information', views.event_views, name='info'),
    
    path('booking/bus/search/<slug>', views.add_to_bookings, name='addhire'),
    
    path('bus/register', views.bus_hire_view, name='bookbus'),
    
    path('aboutus', views.aboutUs_page, name='about'),
    
    path('faQ', views.faQ_page, name='faQ'),
        
    path('booking/bus/search', views.SearchView.as_view(), name='searchpath'),
    
    path('booking/<int:pk>', views.BookingBusDetail.as_view(), name='bookingdetail'),
    
    path("booking/bus/direction/<int:pk>/<slug>", views.DirectionDetail.as_view(), name="direction_detail"),

    # path('hiring', views.hirebus, name='hiringbus'),

    # path('booking', booking_views, name='book'),
    
    # path(
        
    #     "informaa1276765433niaganalanajanaanaianau34aranaeanawana324apanaoana456543akanqanyana56banatanhanaban45456774",

    #     name='booked'
    
    # )
    
]

core/models.py
import datetime

from django.shortcuts import reverse
from django.db import models
from django.utils import timezone
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

from accounts.models import User
from location_app.models import Location, Directions

# Create your models here.

class EventType(models.Model):
    name =  models.CharField(max_length=252)
    images = models.ImageField(upload_to='events_folder/', default='fixed_pic.jpg')
    descriptions = models.TextField(max_length=1330)
    slug = models.SlugField()
    
    def __str__(self):
        return self.name


class BusNumber(models.Model):
    bus_number = models.IntegerField(default=22)
    
    def __str__(self):
        number = self.bus_number
        return str(number)



class BookingBus(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    direction = models.ForeignKey(Directions, on_delete=models.CASCADE)
    hired = models.BooleanField(default=False)
    start_date = models.DateTimeField(auto_now_add=True)
    hired_date = models.DateTimeField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse("core:home", kwargs={
            'slug': self.slug
        })

    class Meta:
        verbose_name_plural = 'HiringBus'

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.user.username

core/forms.py
from django import forms
# from .models import BookingBus

# class BookingBForm(forms.ModelForm):
    
#     class Meta:
#         model = HiringB
#         fields = [
#             'your_location',
#             'destination',
#         ]
#     def clean(self, *args, **kwargs):
#         return super(BookingBForm, self).clean(*args, **kwargs)

# class HiringBForm(forms.ModelForm):
    
#     class Meta:
#         model = BookingBus
#         fields = [
#             'event_type',
#             'how_many_bus_are_needed',
#             'number_of_sitters',
#             'particular_locations',
#             'destination',
#             'date_and_time'
#         ]

core/views.py
from itertools import chain

from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist

from accounts.models import User
from location_app.models import Location, Directions

from .models import (
    
    BookingBus,
    
    EventType
    
    )



    
# this is the homepage
# @login_required
def index_views(request):
    
    # user = User.objects.get(username=request.user)
    
    booked_b = Directions.objects.all()[:3]
    
    context = {
        
        'book_b': booked_b,
        
    }
    return render(request, 'home_templates/index.html', context)





# this is the bus search and book pages
class SearchView(ListView):
    
    template_name = 'home_templates/searchpage.html'
    
    paginate_by = 20
    
    count = 0
    
    # for getting context_data
    def get_context_data(self, *args, **kwargs):
        
        context = super().get_context_data(*args, **kwargs)
        
        context['count'] = self.count or 0
        
        context['query'] = self.request.GET.get('q')
        
        return context
    
    # for getting queryset
    def get_queryset(self):
        
        request = self.request
        
        query = request.GET.get('q', None)
        
        if query is not None:
            
            direction_results = Directions.objects.search(query)
            
            queryset_chain = chain(
                
                direction_results,
                
            )
            qs = sorted(
                
                queryset_chain,
                
                key=lambda instance: instance.pk,
                
                reverse=True
            )
            
            self.count = len(qs)
            
            return qs
        
        return Directions.objects.none()



# this is for viewing events
@login_required
def event_views(request):
    
    user = User.objects.get(username=request.user)
    
    # booked_b = BookingB.objects.all()
    
    hire_b = HiringBus.objects.filter(user=user)
    
    context = {
        # 'book_b': booked_b,
        'hire_b': hire_b
    }
    return render(request, 'home_templates/booked.html', context)




def bus_hire_view(request):
    bus_directions = Directions.objects.all()[:8]
    
    context = {
        
        'bus_directions':bus_directions
        
    }
    return render(request, 'home_templates/bookbus.html', context)



#used to book for bus 
@login_required
def add_to_bookings(request, slug):
    directions = get_object_or_404(Directions, slug=slug)

    hire_qs = BookingBus.objects.filter(
        
        user=request.user,
        
        direction=directions,
        
        hired=True
        
    )

    if hire_qs.exists():
        
        messages.info(request, 'this booking already exist')
        
        return redirect('/home', slug=slug)
    
    else:
        
        hire_bus, created = HiringBus.objects.get_or_create(
            
            user=request.user,
            
            direction=directions,
            
            hired=True
            
        )[:2]
        
        hire_bus.save()
        
        messages.info(
            
            request,
            
            'Your Booking was Successful, Feel Free to book another'
            
        )  
    return redirect('/home', slug=slug)


    
    
    # hire_qs = Hiring.objects.filter(user=request.user, hired=True)
    # if hire_qs.exists():
    #     hire = hire_qs[0]
    #     #check if the hiring bus is in the hire
    #     if hire.direction.filter(direction__slug=directions.slug).exists():
    #         hire_bus
        


# Create your views here.
# @login_required
# def booking_views(request):
    # if request.method == 'POST':
    #     book_form = BookingBForm(request.POST)
    #     if book_form.is_valid():
    #         your_locations = book_form.cleaned_data.get('your_location')
    #         destinations = book_form.cleaned_data.get('destination')
    #         users = User.objects.get(username=request.user)
    #         book_saver = HiringB.objects.create(
    #             user=request.user,
    #             your_location=your_locations,
    #             destination=destinations
    #         )
    #         book_saver.save()
    #         # book_form.instance = request.user
    #         # book_form.save()
    #         return redirect('/events/information')
    # else:
    #     book_form = BookingBForm()
    # context = {
    #     'book_form':book_form
    # }
    # return render(request, 'about.html', context)
    # return render(request, 'home_templates/booking.html', context)





def aboutUs_page(request):
    
    return render(request, 'order/about.html')

def faQ_page(request):
    
    return render(request, 'order/faQ.html')

class BookingBusDetail(DetailView):
    
    model = BookingBus
    
    template_name='applications/properties-single.html'

class DirectionDetail(DetailView):
    
    model = Directions
    
    template_name = 'applications/direction-single.html'

core/templates/base_folder/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include "base_folder/head.html" %}
<body class="">
    {% block blockbody %}
    {% endblock blockbody %}
    {% include "base_folder/footer.html" %}
    {% include "base_folder/scripts.html" %}
</body>
</html>

core/templates/base_folder/footer.html
{% load static %}
<!-- START footer -->
<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">BusBuggy</h2>
                    <p>We go anywhere you want to go, <br> giving you the best for <br> actual price.</p>
                    <ul class="ftco-footer-social list-unstyled mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">About Us</h2>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'core:about' %}"><span class="icon-long-arrow-right mr-2"></span>About Us</a></li>
                        <li><a href=" {% url 'core:faQ' %} "><span class="icon-long-arrow-right mr-2"></span>Meet the team</a></li>
                        <li><a href=" {% url 'core:faQ' %} "><span class="icon-long-arrow-right mr-2"></span>Terms and Conditions</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Company</h2>
                    <ul class="list-unstyled">
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Carrier</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Blog</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Contact</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Help</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Discover</h2>
                    <ul class="list-unstyled">
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>InstaCash</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Zanzra</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Hedge</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>BugPress</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">15 Otunba Sheki St. Tedi Town,
                                   Ojo Barrack, Lagos, Nigeria</span></li>
                            <li><a href="#"><span class="icon icon-phone"></span><span class="text">+234 901 576
                                        5454</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope pr-4"></span><span
                                        class="text">info@busbuggy.com</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | </i> by <a
                        href="https://colorlib.com" target="">BusBuggy</a>

                </p>
            </div>
        </div>
    </div>
</footer>
<!-- END footer -->

core/templates/base_folder/head.html
{% load static %}
<head>
    <title>BusBuggy: home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- start file here  -->
    <link rel="icon" href="{% static 'images/logo-1.png' %}" type="image/png">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900&display=swap"
        rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- end file here -->
</head>

core/templates/base_folder/scripts.html
{% load static %}



<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/aos.js' %}"></script>

<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>

<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


<!-- loader -->
<!-- <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
            stroke="#F96D00" /></svg></div> -->